# Stage 1: Build Angular frontd

FROM node:18-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ ./

RUN npm run build -- --configuration=production   

# Stage 2: Serve with Nginx

FROM nginx:alpine

# Copy built static files
COPY frontend/dist/angular-15-crud /usr/share/nginx/html

# Copy Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
